root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "tmp/main"
full_bin = "tmp/main"
include_ext = ["go"]
exclude_dir = ["tmp", "migrations", "docs"]
delay = 200

[log]
time = false

[misc]
clean_on_exit = true
