// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_request.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acquireDocumentMergeLock = `-- name: AcquireDocumentMergeLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Serializes merges of one document: every transaction that moves main takes
// this lock first. hashtextextended maps the UUID to a bigint key space.
func (q *Queries) AcquireDocumentMergeLock(ctx context.Context, dollar_1 string) error {
	_, err := q.db.Exec(ctx, acquireDocumentMergeLock, dollar_1)
	return err
}

const closeChangeRequest = `-- name: CloseChangeRequest :one
UPDATE change_request
SET status = 'closed',
    close_note = $2,
    closed_at = now(),
    updated_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, document_id, base_revision_id, kind, title, content_markdown, status, opened_by, merged_by, close_note, created_at, updated_at, closed_at, workstream_id
`

type CloseChangeRequestParams struct {
	ID        uuid.UUID `json:"id"`
	CloseNote string    `json:"close_note"`
}

func (q *Queries) CloseChangeRequest(ctx context.Context, arg CloseChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, closeChangeRequest, arg.ID, arg.CloseNote)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BaseRevisionID,
		&i.Kind,
		&i.Title,
		&i.ContentMarkdown,
		&i.Status,
		&i.OpenedBy,
		&i.MergedBy,
		&i.CloseNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.WorkstreamID,
	)
	return i, err
}

const createCRComment = `-- name: CreateCRComment :one
INSERT INTO cr_comment (change_request_id, parent_id, created_by, body, diff_anchor)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, change_request_id, parent_id, created_by, body, diff_anchor, deleted_at, created_at
`

type CreateCRCommentParams struct {
	ChangeRequestID uuid.UUID     `json:"change_request_id"`
	ParentID        uuid.NullUUID `json:"parent_id"`
	CreatedBy       uuid.UUID     `json:"created_by"`
	Body            string        `json:"body"`
	DiffAnchor      []byte        `json:"diff_anchor"`
}

func (q *Queries) CreateCRComment(ctx context.Context, arg CreateCRCommentParams) (CrComment, error) {
	row := q.db.QueryRow(ctx, createCRComment,
		arg.ChangeRequestID,
		arg.ParentID,
		arg.CreatedBy,
		arg.Body,
		arg.DiffAnchor,
	)
	var i CrComment
	err := row.Scan(
		&i.ID,
		&i.ChangeRequestID,
		&i.ParentID,
		&i.CreatedBy,
		&i.Body,
		&i.DiffAnchor,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createChangeRequest = `-- name: CreateChangeRequest :one
INSERT INTO change_request (document_id, base_revision_id, kind, title, content_markdown, opened_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, document_id, base_revision_id, kind, title, content_markdown, status, opened_by, merged_by, close_note, created_at, updated_at, closed_at, workstream_id
`

type CreateChangeRequestParams struct {
	DocumentID      uuid.UUID `json:"document_id"`
	BaseRevisionID  uuid.UUID `json:"base_revision_id"`
	Kind            string    `json:"kind"`
	Title           string    `json:"title"`
	ContentMarkdown string    `json:"content_markdown"`
	OpenedBy        uuid.UUID `json:"opened_by"`
}

func (q *Queries) CreateChangeRequest(ctx context.Context, arg CreateChangeRequestParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, createChangeRequest,
		arg.DocumentID,
		arg.BaseRevisionID,
		arg.Kind,
		arg.Title,
		arg.ContentMarkdown,
		arg.OpenedBy,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BaseRevisionID,
		&i.Kind,
		&i.Title,
		&i.ContentMarkdown,
		&i.Status,
		&i.OpenedBy,
		&i.MergedBy,
		&i.CloseNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.WorkstreamID,
	)
	return i, err
}

const createChangeRequestFromWorkstream = `-- name: CreateChangeRequestFromWorkstream :one
INSERT INTO change_request (
    document_id, base_revision_id, workstream_id, kind,
    title, content_markdown, opened_by
)
VALUES ($1, $2, $3, 'edit', $4, $5, $6)
RETURNING id, document_id, base_revision_id, kind, title, content_markdown, status, opened_by, merged_by, close_note, created_at, updated_at, closed_at, workstream_id
`

type CreateChangeRequestFromWorkstreamParams struct {
	DocumentID      uuid.UUID     `json:"document_id"`
	BaseRevisionID  uuid.UUID     `json:"base_revision_id"`
	WorkstreamID    uuid.NullUUID `json:"workstream_id"`
	Title           string        `json:"title"`
	ContentMarkdown string        `json:"content_markdown"`
	OpenedBy        uuid.UUID     `json:"opened_by"`
}

func (q *Queries) CreateChangeRequestFromWorkstream(ctx context.Context, arg CreateChangeRequestFromWorkstreamParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, createChangeRequestFromWorkstream,
		arg.DocumentID,
		arg.BaseRevisionID,
		arg.WorkstreamID,
		arg.Title,
		arg.ContentMarkdown,
		arg.OpenedBy,
	)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BaseRevisionID,
		&i.Kind,
		&i.Title,
		&i.ContentMarkdown,
		&i.Status,
		&i.OpenedBy,
		&i.MergedBy,
		&i.CloseNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.WorkstreamID,
	)
	return i, err
}

const getCRComment = `-- name: GetCRComment :one
SELECT id, change_request_id, parent_id, created_by, body, diff_anchor, deleted_at, created_at
FROM cr_comment
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCRComment(ctx context.Context, id uuid.UUID) (CrComment, error) {
	row := q.db.QueryRow(ctx, getCRComment, id)
	var i CrComment
	err := row.Scan(
		&i.ID,
		&i.ChangeRequestID,
		&i.ParentID,
		&i.CreatedBy,
		&i.Body,
		&i.DiffAnchor,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getChangeRequestByID = `-- name: GetChangeRequestByID :one
SELECT id, document_id, base_revision_id, kind, title, content_markdown, status, opened_by, merged_by, close_note, created_at, updated_at, closed_at, workstream_id FROM change_request
WHERE id = $1
`

func (q *Queries) GetChangeRequestByID(ctx context.Context, id uuid.UUID) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, getChangeRequestByID, id)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BaseRevisionID,
		&i.Kind,
		&i.Title,
		&i.ContentMarkdown,
		&i.Status,
		&i.OpenedBy,
		&i.MergedBy,
		&i.CloseNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.WorkstreamID,
	)
	return i, err
}

const listCRComments = `-- name: ListCRComments :many
SELECT id, change_request_id, parent_id, created_by, body, diff_anchor, deleted_at, created_at
FROM cr_comment
WHERE change_request_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListCRComments(ctx context.Context, changeRequestID uuid.UUID) ([]CrComment, error) {
	rows, err := q.db.Query(ctx, listCRComments, changeRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CrComment{}
	for rows.Next() {
		var i CrComment
		if err := rows.Scan(
			&i.ID,
			&i.ChangeRequestID,
			&i.ParentID,
			&i.CreatedBy,
			&i.Body,
			&i.DiffAnchor,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeRequestsForDocument = `-- name: ListChangeRequestsForDocument :many
SELECT id, document_id, base_revision_id, kind, title, content_markdown, status, opened_by, merged_by, close_note, created_at, updated_at, closed_at, workstream_id
FROM change_request
WHERE document_id = $1
ORDER BY created_at DESC
`

// Open CRs are what review pages care about; merged and closed ones are
// history the document page lists in full and lets callers group by status.
func (q *Queries) ListChangeRequestsForDocument(ctx context.Context, documentID uuid.UUID) ([]ChangeRequest, error) {
	rows, err := q.db.Query(ctx, listChangeRequestsForDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeRequest{}
	for rows.Next() {
		var i ChangeRequest
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.BaseRevisionID,
			&i.Kind,
			&i.Title,
			&i.ContentMarkdown,
			&i.Status,
			&i.OpenedBy,
			&i.MergedBy,
			&i.CloseNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClosedAt,
			&i.WorkstreamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChangeRequestMerged = `-- name: MarkChangeRequestMerged :one
UPDATE change_request
SET status = 'merged',
    merged_by = $2,
    updated_at = now()
WHERE id = $1 AND status = 'open'
RETURNING id, document_id, base_revision_id, kind, title, content_markdown, status, opened_by, merged_by, close_note, created_at, updated_at, closed_at, workstream_id
`

type MarkChangeRequestMergedParams struct {
	ID       uuid.UUID     `json:"id"`
	MergedBy uuid.NullUUID `json:"merged_by"`
}

// The status predicate makes "merge" and "close" race-safe without a lock:
// whichever statement runs second matches no row and reports the conflict.
func (q *Queries) MarkChangeRequestMerged(ctx context.Context, arg MarkChangeRequestMergedParams) (ChangeRequest, error) {
	row := q.db.QueryRow(ctx, markChangeRequestMerged, arg.ID, arg.MergedBy)
	var i ChangeRequest
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.BaseRevisionID,
		&i.Kind,
		&i.Title,
		&i.ContentMarkdown,
		&i.Status,
		&i.OpenedBy,
		&i.MergedBy,
		&i.CloseNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.WorkstreamID,
	)
	return i, err
}

const softDeleteCRComment = `-- name: SoftDeleteCRComment :exec
UPDATE cr_comment
SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCRComment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCRComment, id)
	return err
}

const listOpenChangeRequestsForProject = `-- name: ListOpenChangeRequestsForProject :many
SELECT cr.id, cr.document_id, d.title AS document_title, cr.base_revision_id,
       cr.kind, cr.title, cr.status, cr.opened_by, cr.created_at, cr.updated_at,
       cr.workstream_id
FROM change_request cr
JOIN document d ON d.id = cr.document_id
WHERE d.project_id = $1 AND cr.status = 'open'
ORDER BY cr.updated_at DESC
`

type ListOpenChangeRequestsForProjectRow struct {
	ID             uuid.UUID     `json:"id"`
	DocumentID     uuid.UUID     `json:"document_id"`
	DocumentTitle  string        `json:"document_title"`
	BaseRevisionID uuid.UUID     `json:"base_revision_id"`
	Kind           string        `json:"kind"`
	Title          string        `json:"title"`
	Status         string        `json:"status"`
	OpenedBy       uuid.UUID     `json:"opened_by"`
	CreatedAt      time.Time     `json:"created_at"`
	UpdatedAt      time.Time     `json:"updated_at"`
	WorkstreamID   uuid.NullUUID `json:"workstream_id"`
}

// The project page's review queue: every open proposal across the project's
// documents, newest activity first. The document title rides along so the list
// reads without a second fetch, and the snapshot body stays off the list shape.
func (q *Queries) ListOpenChangeRequestsForProject(ctx context.Context, projectID uuid.UUID) ([]ListOpenChangeRequestsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listOpenChangeRequestsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenChangeRequestsForProjectRow{}
	for rows.Next() {
		var i ListOpenChangeRequestsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.DocumentTitle,
			&i.BaseRevisionID,
			&i.Kind,
			&i.Title,
			&i.Status,
			&i.OpenedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkstreamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
