// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_revision.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createDocumentRevision = `-- name: CreateDocumentRevision :one
INSERT INTO document_revision (document_id, seq, title, content_markdown, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, document_id, seq, title, content_markdown, created_by, created_at
`

type CreateDocumentRevisionParams struct {
	DocumentID      uuid.UUID `json:"document_id"`
	Seq             int64     `json:"seq"`
	Title           string    `json:"title"`
	ContentMarkdown string    `json:"content_markdown"`
	CreatedBy       uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateDocumentRevision(ctx context.Context, arg CreateDocumentRevisionParams) (DocumentRevision, error) {
	row := q.db.QueryRow(ctx, createDocumentRevision,
		arg.DocumentID,
		arg.Seq,
		arg.Title,
		arg.ContentMarkdown,
		arg.CreatedBy,
	)
	var i DocumentRevision
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Seq,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentRevision = `-- name: GetDocumentRevision :one
SELECT id, document_id, seq, title, content_markdown, created_by, created_at FROM document_revision
WHERE id = $1 AND document_id = $2
`

type GetDocumentRevisionParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
}

func (q *Queries) GetDocumentRevision(ctx context.Context, arg GetDocumentRevisionParams) (DocumentRevision, error) {
	row := q.db.QueryRow(ctx, getDocumentRevision, arg.ID, arg.DocumentID)
	var i DocumentRevision
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Seq,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentRevisions = `-- name: ListDocumentRevisions :many
SELECT id, document_id, seq, title, created_by, created_at
FROM document_revision
WHERE document_id = $1
ORDER BY seq DESC
`

type ListDocumentRevisionsRow struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	Seq        int64     `json:"seq"`
	Title      string    `json:"title"`
	CreatedBy  uuid.UUID `json:"created_by"`
	CreatedAt  time.Time `json:"created_at"`
}

// The body is deliberately left out: history lists render titles only, and a
// long document's full text per row would dwarf every other page's payload.
func (q *Queries) ListDocumentRevisions(ctx context.Context, documentID uuid.UUID) ([]ListDocumentRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentRevisions, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentRevisionsRow{}
	for rows.Next() {
		var i ListDocumentRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Seq,
			&i.Title,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextRevisionSeq = `-- name: NextRevisionSeq :one
SELECT coalesce(max(seq), 0) + 1 AS seq
FROM document_revision
WHERE document_id = $1
`

// Called inside the merge transaction, after the per-document advisory lock,
// so concurrent merges of the same document serialize here rather than race.
func (q *Queries) NextRevisionSeq(ctx context.Context, documentID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextRevisionSeq, documentID)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const setDocumentHead = `-- name: SetDocumentHead :exec
UPDATE document
SET head_revision_id = $2,
    title = $3,
    content_markdown = $4,
    updated_at = now()
WHERE id = $1
`

type SetDocumentHeadParams struct {
	ID              uuid.UUID     `json:"id"`
	HeadRevisionID  uuid.NullUUID `json:"head_revision_id"`
	Title           string        `json:"title"`
	ContentMarkdown string        `json:"content_markdown"`
}

// Moves main forward. The document row's title and content_markdown are kept
// as an exact mirror of the head revision so the existing single-row reads
// (list pages, GET document) never need a join.
func (q *Queries) SetDocumentHead(ctx context.Context, arg SetDocumentHeadParams) error {
	_, err := q.db.Exec(ctx, setDocumentHead,
		arg.ID,
		arg.HeadRevisionID,
		arg.Title,
		arg.ContentMarkdown,
	)
	return err
}
