// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO document (project_id, title, created_by)
VALUES ($1, $2, $3)
RETURNING id, project_id, title, content_markdown, created_by, created_at, updated_at, deleted_at, head_revision_id
`

type CreateDocumentParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Title     string    `json:"title"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument, arg.ProjectID, arg.Title, arg.CreatedBy)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HeadRevisionID,
	)
	return i, err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT id, project_id, title, content_markdown, created_by, created_at, updated_at, deleted_at, head_revision_id FROM document
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HeadRevisionID,
	)
	return i, err
}

const getDocumentByIDIncludingDeleted = `-- name: GetDocumentByIDIncludingDeleted :one
SELECT id, project_id, title, content_markdown, created_by, created_at, updated_at, deleted_at, head_revision_id FROM document
WHERE id = $1
`

func (q *Queries) GetDocumentByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentByIDIncludingDeleted, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HeadRevisionID,
	)
	return i, err
}

const getDocumentForInitialVersion = `-- name: GetDocumentForInitialVersion :one
SELECT id, project_id, title, content_markdown, created_by, created_at, updated_at, deleted_at, head_revision_id FROM document
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

// Locks an active document while the first immutable version is created, so
// two editors cannot both observe an empty head and create revision 1.
func (q *Queries) GetDocumentForInitialVersion(ctx context.Context, id uuid.UUID) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentForInitialVersion, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HeadRevisionID,
	)
	return i, err
}

const listDocumentsForProject = `-- name: ListDocumentsForProject :many
SELECT id, project_id, title, head_revision_id, created_by, created_at, updated_at, deleted_at
FROM document
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
`

type ListDocumentsForProjectRow struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	Title          string             `json:"title"`
	HeadRevisionID uuid.NullUUID      `json:"head_revision_id"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

// The body is deliberately left out: a list of documents would otherwise carry
// a megabyte of Markdown per row for a page that only renders titles.
func (q *Queries) ListDocumentsForProject(ctx context.Context, projectID uuid.UUID) ([]ListDocumentsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsForProjectRow{}
	for rows.Next() {
		var i ListDocumentsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.HeadRevisionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedDocumentsForProject = `-- name: ListDeletedDocumentsForProject :many
SELECT id, project_id, title, head_revision_id, created_by, created_at, updated_at, deleted_at
FROM document
WHERE project_id = $1 AND deleted_at IS NOT NULL
ORDER BY updated_at DESC
`

// The same summary shape as ListDocumentsForProject, but for soft-deleted
// rows, so a manager can find and restore a document that was taken out.
func (q *Queries) ListDeletedDocumentsForProject(ctx context.Context, projectID uuid.UUID) ([]ListDocumentsForProjectRow, error) {
	rows, err := q.db.Query(ctx, listDeletedDocumentsForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentsForProjectRow{}
	for rows.Next() {
		var i ListDocumentsForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.HeadRevisionID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreDocument = `-- name: RestoreDocument :exec
UPDATE document
SET deleted_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreDocument, id)
	return err
}

const softDeleteDocument = `-- name: SoftDeleteDocument :exec
UPDATE document
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDocument, id)
	return err
}
