// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organization (name, is_personal, created_by)
VALUES ($1, $2, $3)
RETURNING id, name, is_personal, members_can_invite, created_by, created_at, updated_at, deleted_at
`

type CreateOrganizationParams struct {
	Name       string    `json:"name"`
	IsPersonal bool      `json:"is_personal"`
	CreatedBy  uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization, arg.Name, arg.IsPersonal, arg.CreatedBy)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.MembersCanInvite,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeletedOrganizationByID = `-- name: GetDeletedOrganizationByID :one
SELECT id, name, is_personal, members_can_invite, created_by, created_at, updated_at, deleted_at FROM organization
WHERE id = $1
`

func (q *Queries) GetDeletedOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getDeletedOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.MembersCanInvite,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, name, is_personal, members_can_invite, created_by, created_at, updated_at, deleted_at FROM organization
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.MembersCanInvite,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDeletedOrganizationsForUser = `-- name: ListDeletedOrganizationsForUser :many
SELECT o.id, o.name, o.is_personal, o.members_can_invite, o.created_by, o.created_at, o.updated_at, o.deleted_at, m.role
FROM organization o
JOIN organization_member m ON m.organization_id = o.id
WHERE m.user_id = $1 AND o.deleted_at IS NOT NULL AND m.role = 'admin'
ORDER BY o.deleted_at DESC
`

// The caller's own admin membership is the gate: only an admin of a deleted
// org can see and restore it, and a non-admin member never appears here.
func (q *Queries) ListDeletedOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listDeletedOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPersonal,
			&i.MembersCanInvite,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrganizationsForUser = `-- name: ListOrganizationsForUser :many
SELECT o.id, o.name, o.is_personal, o.members_can_invite, o.created_by, o.created_at, o.updated_at, o.deleted_at, m.role
FROM organization o
JOIN organization_member m ON m.organization_id = o.id
WHERE m.user_id = $1 AND o.deleted_at IS NULL
ORDER BY o.is_personal DESC, o.name
`

type ListOrganizationsForUserRow struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	IsPersonal       bool               `json:"is_personal"`
	MembersCanInvite bool               `json:"members_can_invite"`
	CreatedBy        uuid.UUID          `json:"created_by"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Role             string             `json:"role"`
}

func (q *Queries) ListOrganizationsForUser(ctx context.Context, userID uuid.UUID) ([]ListOrganizationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationsForUserRow{}
	for rows.Next() {
		var i ListOrganizationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPersonal,
			&i.MembersCanInvite,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreOrganization = `-- name: RestoreOrganization :exec
UPDATE organization
SET deleted_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreOrganization, id)
	return err
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organization
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, id)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organization
SET name = coalesce($1, name),
    members_can_invite = coalesce($2, members_can_invite),
    updated_at = now()
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, name, is_personal, members_can_invite, created_by, created_at, updated_at, deleted_at
`

type UpdateOrganizationParams struct {
	Name             pgtype.Text `json:"name"`
	MembersCanInvite pgtype.Bool `json:"members_can_invite"`
	ID               uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.Name, arg.MembersCanInvite, arg.ID)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPersonal,
		&i.MembersCanInvite,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
