// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_member.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOrganizationAdmins = `-- name: CountOrganizationAdmins :one
SELECT count(*) FROM organization_member
WHERE organization_id = $1 AND role = 'admin'
`

func (q *Queries) CountOrganizationAdmins(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationAdmins, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrganizationMembers = `-- name: CountOrganizationMembers :one
SELECT count(*) FROM organization_member
WHERE organization_id = $1
`

func (q *Queries) CountOrganizationMembers(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOrganizationMembers, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrganizationMember = `-- name: CreateOrganizationMember :one
INSERT INTO organization_member (organization_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
RETURNING id, organization_id, user_id, role, invited_by, joined_at
`

type CreateOrganizationMemberParams struct {
	OrganizationID uuid.UUID     `json:"organization_id"`
	UserID         uuid.UUID     `json:"user_id"`
	Role           string        `json:"role"`
	InvitedBy      uuid.NullUUID `json:"invited_by"`
}

func (q *Queries) CreateOrganizationMember(ctx context.Context, arg CreateOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, createOrganizationMember,
		arg.OrganizationID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const deleteOrganizationMember = `-- name: DeleteOrganizationMember :exec
DELETE FROM organization_member
WHERE id = $1
`

func (q *Queries) DeleteOrganizationMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOrganizationMember, id)
	return err
}

const getOrganizationMember = `-- name: GetOrganizationMember :one
SELECT id, organization_id, user_id, role, invited_by, joined_at FROM organization_member
WHERE organization_id = $1 AND user_id = $2
`

type GetOrganizationMemberParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

func (q *Queries) GetOrganizationMember(ctx context.Context, arg GetOrganizationMemberParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMember, arg.OrganizationID, arg.UserID)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const getOrganizationMemberByID = `-- name: GetOrganizationMemberByID :one
SELECT id, organization_id, user_id, role, invited_by, joined_at FROM organization_member
WHERE id = $1
`

func (q *Queries) GetOrganizationMemberByID(ctx context.Context, id uuid.UUID) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, getOrganizationMemberByID, id)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}

const listOrganizationMembers = `-- name: ListOrganizationMembers :many
SELECT m.id, m.organization_id, m.user_id, m.role, m.invited_by, m.joined_at, u.email, u.name
FROM organization_member m
JOIN user_account u ON u.id = m.user_id
WHERE m.organization_id = $1
ORDER BY m.joined_at
`

type ListOrganizationMembersRow struct {
	ID             uuid.UUID     `json:"id"`
	OrganizationID uuid.UUID     `json:"organization_id"`
	UserID         uuid.UUID     `json:"user_id"`
	Role           string        `json:"role"`
	InvitedBy      uuid.NullUUID `json:"invited_by"`
	JoinedAt       time.Time     `json:"joined_at"`
	Email          string        `json:"email"`
	Name           string        `json:"name"`
}

func (q *Queries) ListOrganizationMembers(ctx context.Context, organizationID uuid.UUID) ([]ListOrganizationMembersRow, error) {
	rows, err := q.db.Query(ctx, listOrganizationMembers, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrganizationMembersRow{}
	for rows.Next() {
		var i ListOrganizationMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.JoinedAt,
			&i.Email,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganizationMemberRole = `-- name: UpdateOrganizationMemberRole :one
UPDATE organization_member
SET role = $2
WHERE id = $1
RETURNING id, organization_id, user_id, role, invited_by, joined_at
`

type UpdateOrganizationMemberRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateOrganizationMemberRole(ctx context.Context, arg UpdateOrganizationMemberRoleParams) (OrganizationMember, error) {
	row := q.db.QueryRow(ctx, updateOrganizationMemberRole, arg.ID, arg.Role)
	var i OrganizationMember
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.JoinedAt,
	)
	return i, err
}
