// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_invitation.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOrganizationInvitation = `-- name: CreateOrganizationInvitation :one
INSERT INTO organization_invitation (organization_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at
`

type CreateOrganizationInvitationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Email          string    `json:"email"`
	Role           string    `json:"role"`
	TokenHash      string    `json:"token_hash"`
	InvitedBy      uuid.UUID `json:"invited_by"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateOrganizationInvitation(ctx context.Context, arg CreateOrganizationInvitationParams) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, createOrganizationInvitation,
		arg.OrganizationID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInvitations = `-- name: DeleteExpiredInvitations :execrows
DELETE FROM organization_invitation
WHERE expires_at < $1
`

func (q *Queries) DeleteExpiredInvitations(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredInvitations, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOrganizationInvitationByID = `-- name: GetOrganizationInvitationByID :one
SELECT id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM organization_invitation
WHERE id = $1
`

func (q *Queries) GetOrganizationInvitationByID(ctx context.Context, id uuid.UUID) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getOrganizationInvitationByID, id)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getValidInvitationByTokenHash = `-- name: GetValidInvitationByTokenHash :one
SELECT id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM organization_invitation
WHERE token_hash = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetValidInvitationByTokenHash(ctx context.Context, tokenHash string) (OrganizationInvitation, error) {
	row := q.db.QueryRow(ctx, getValidInvitationByTokenHash, tokenHash)
	var i OrganizationInvitation
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOrganizationInvitations = `-- name: ListOrganizationInvitations :many
SELECT id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM organization_invitation
WHERE organization_id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizationInvitations(ctx context.Context, organizationID uuid.UUID) ([]OrganizationInvitation, error) {
	rows, err := q.db.Query(ctx, listOrganizationInvitations, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitation{}
	for rows.Next() {
		var i OrganizationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitationsForEmail = `-- name: ListPendingInvitationsForEmail :many
SELECT id, organization_id, email, role, token_hash, invited_by, expires_at, accepted_at, revoked_at, created_at FROM organization_invitation
WHERE lower(email) = lower($1)
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) ListPendingInvitationsForEmail(ctx context.Context, lower string) ([]OrganizationInvitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitationsForEmail, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrganizationInvitation{}
	for rows.Next() {
		var i OrganizationInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvitationAccepted = `-- name: MarkInvitationAccepted :exec
UPDATE organization_invitation
SET accepted_at = now()
WHERE id = $1
`

func (q *Queries) MarkInvitationAccepted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markInvitationAccepted, id)
	return err
}

const revokeInvitation = `-- name: RevokeInvitation :exec
UPDATE organization_invitation
SET revoked_at = now()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
`

func (q *Queries) RevokeInvitation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeInvitation, id)
	return err
}
