// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProjectPermissionGrant = `-- name: CreateProjectPermissionGrant :one
INSERT INTO project_permission_grant (project_id, user_id, permission_key, granted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, user_id, permission_key) DO NOTHING
RETURNING id, project_id, user_id, permission_key, granted_by, created_at
`

type CreateProjectPermissionGrantParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	UserID        uuid.UUID `json:"user_id"`
	PermissionKey string    `json:"permission_key"`
	GrantedBy     uuid.UUID `json:"granted_by"`
}

func (q *Queries) CreateProjectPermissionGrant(ctx context.Context, arg CreateProjectPermissionGrantParams) (ProjectPermissionGrant, error) {
	row := q.db.QueryRow(ctx, createProjectPermissionGrant,
		arg.ProjectID,
		arg.UserID,
		arg.PermissionKey,
		arg.GrantedBy,
	)
	var i ProjectPermissionGrant
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.PermissionKey,
		&i.GrantedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectPermissionGrant = `-- name: DeleteProjectPermissionGrant :exec
DELETE FROM project_permission_grant
WHERE project_id = $1 AND user_id = $2 AND permission_key = $3
`

type DeleteProjectPermissionGrantParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	UserID        uuid.UUID `json:"user_id"`
	PermissionKey string    `json:"permission_key"`
}

func (q *Queries) DeleteProjectPermissionGrant(ctx context.Context, arg DeleteProjectPermissionGrantParams) error {
	_, err := q.db.Exec(ctx, deleteProjectPermissionGrant, arg.ProjectID, arg.UserID, arg.PermissionKey)
	return err
}

const deleteUserGrantsInOrganization = `-- name: DeleteUserGrantsInOrganization :execrows
DELETE FROM project_permission_grant g
USING project p
WHERE g.project_id = p.id
  AND p.organization_id = $1
  AND g.user_id = $2
`

type DeleteUserGrantsInOrganizationParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

// Used when a member is removed from an org: their grants on that org's
// projects go with them, so removal actually removes access.
func (q *Queries) DeleteUserGrantsInOrganization(ctx context.Context, arg DeleteUserGrantsInOrganizationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserGrantsInOrganization, arg.OrganizationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT key, description FROM permission
ORDER BY key
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.Key, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectPermissionGrants = `-- name: ListProjectPermissionGrants :many
SELECT g.id, g.project_id, g.user_id, g.permission_key, g.granted_by, g.created_at, u.email, u.name AS user_name
FROM project_permission_grant g
JOIN user_account u ON u.id = g.user_id
WHERE g.project_id = $1
ORDER BY u.email, g.permission_key
`

type ListProjectPermissionGrantsRow struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	UserID        uuid.UUID `json:"user_id"`
	PermissionKey string    `json:"permission_key"`
	GrantedBy     uuid.UUID `json:"granted_by"`
	CreatedAt     time.Time `json:"created_at"`
	Email         string    `json:"email"`
	UserName      string    `json:"user_name"`
}

func (q *Queries) ListProjectPermissionGrants(ctx context.Context, projectID uuid.UUID) ([]ListProjectPermissionGrantsRow, error) {
	rows, err := q.db.Query(ctx, listProjectPermissionGrants, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectPermissionGrantsRow{}
	for rows.Next() {
		var i ListProjectPermissionGrantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.PermissionKey,
			&i.GrantedBy,
			&i.CreatedAt,
			&i.Email,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionKeysForProject = `-- name: ListUserPermissionKeysForProject :many
SELECT permission_key FROM project_permission_grant
WHERE project_id = $1 AND user_id = $2
ORDER BY permission_key
`

type ListUserPermissionKeysForProjectParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) ListUserPermissionKeysForProject(ctx context.Context, arg ListUserPermissionKeysForProjectParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissionKeysForProject, arg.ProjectID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userHasProjectPermission = `-- name: UserHasProjectPermission :one
SELECT EXISTS (
    SELECT 1
    FROM project p
    WHERE p.id = $1
      AND p.deleted_at IS NULL
      AND (
        EXISTS (
          SELECT 1 FROM organization_member m
          WHERE m.organization_id = p.organization_id
            AND m.user_id = $2
            AND m.role = 'admin'
        )
        OR EXISTS (
          SELECT 1 FROM project_permission_grant g
          WHERE g.project_id = p.id
            AND g.user_id = $2
            AND g.permission_key = $3
        )
      )
) AS allowed
`

type UserHasProjectPermissionParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	PermissionKey string    `json:"permission_key"`
}

// The whole authorization model in one query: an org admin passes on any key
// for any project in their org, anyone else passes only with a matching grant.
func (q *Queries) UserHasProjectPermission(ctx context.Context, arg UserHasProjectPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasProjectPermission, arg.ID, arg.UserID, arg.PermissionKey)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}
