// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO project (organization_id, name, created_by)
VALUES ($1, $2, $3)
RETURNING id, organization_id, name, created_by, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	Name           string    `json:"name"`
	CreatedBy      uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OrganizationID, arg.Name, arg.CreatedBy)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, organization_id, name, created_by, created_at, updated_at, deleted_at FROM project
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByIDIncludingDeleted = `-- name: GetProjectByIDIncludingDeleted :one
SELECT id, organization_id, name, created_by, created_at, updated_at, deleted_at FROM project
WHERE id = $1
`

func (q *Queries) GetProjectByIDIncludingDeleted(ctx context.Context, id uuid.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByIDIncludingDeleted, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectsForUserInOrg = `-- name: ListProjectsForUserInOrg :many
SELECT DISTINCT p.id, p.organization_id, p.name, p.created_by, p.created_at, p.updated_at, p.deleted_at
FROM project p
WHERE p.organization_id = $1
  AND p.deleted_at IS NULL
  AND (
    EXISTS (
      SELECT 1 FROM organization_member m
      WHERE m.organization_id = p.organization_id
        AND m.user_id = $2
        AND m.role = 'admin'
    )
    OR EXISTS (
      SELECT 1 FROM project_permission_grant g
      WHERE g.project_id = p.id AND g.user_id = $2
    )
  )
ORDER BY p.created_at DESC
`

type ListProjectsForUserInOrgParams struct {
	OrganizationID uuid.UUID `json:"organization_id"`
	UserID         uuid.UUID `json:"user_id"`
}

// Org admins see every project in the org. Everyone else sees only what they
// hold a grant on, so membership alone conveys no visibility.
func (q *Queries) ListProjectsForUserInOrg(ctx context.Context, arg ListProjectsForUserInOrgParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsForUserInOrg, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedProjectsForOrg = `-- name: ListDeletedProjectsForOrg :many
SELECT id, organization_id, name, created_by, created_at, updated_at, deleted_at
FROM project
WHERE organization_id = $1 AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

// Org admins see every project the org has taken out, so they can find and
// restore one. Nobody else can see deleted projects at all.
func (q *Queries) ListDeletedProjectsForOrg(ctx context.Context, organizationID uuid.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listDeletedProjectsForOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreProject = `-- name: RestoreProject :exec
UPDATE project
SET deleted_at = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) RestoreProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, restoreProject, id)
	return err
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE project
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProjectName = `-- name: UpdateProjectName :one
UPDATE project
SET name = $2, updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, organization_id, name, created_by, created_at, updated_at, deleted_at
`

type UpdateProjectNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectName, arg.ID, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
