// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UserAccount, error)
	DeleteExpiredPasswordResetTokens(ctx context.Context, expiresAt time.Time) (int64, error)
	DeleteExpiredRefreshTokens(ctx context.Context, expiresAt time.Time) (int64, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, lower string) (UserAccount, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (UserAccount, error)
	GetValidPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error)
	InvalidateUserPasswordResetTokens(ctx context.Context, userID uuid.UUID) error
	MarkPasswordResetTokenUsed(ctx context.Context, id uuid.UUID) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
