// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workstream.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const abandonDocumentWorkstream = `-- name: AbandonDocumentWorkstream :one
UPDATE document_workstream
SET status = 'abandoned', abandoned_at = now(), updated_at = now()
WHERE id = $1 AND document_id = $2 AND owner_id = $3 AND status = 'active'
RETURNING id, document_id, owner_id, name, base_revision_id, status, created_at, updated_at, submitted_at, abandoned_at
`

type AbandonDocumentWorkstreamParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	OwnerID    uuid.UUID `json:"owner_id"`
}

func (q *Queries) AbandonDocumentWorkstream(ctx context.Context, arg AbandonDocumentWorkstreamParams) (DocumentWorkstream, error) {
	row := q.db.QueryRow(ctx, abandonDocumentWorkstream, arg.ID, arg.DocumentID, arg.OwnerID)
	var i DocumentWorkstream
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OwnerID,
		&i.Name,
		&i.BaseRevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.AbandonedAt,
	)
	return i, err
}

const createChangeLog = `-- name: CreateChangeLog :one
INSERT INTO change_log (
    workstream_id,
    seq,
    parent_change_log_id,
    message,
    title,
    content_markdown,
    created_by
)
SELECT
    $1,
    coalesce(max(seq), 0) + 1,
    $2,
    $3,
    $4,
    $5,
    $6
FROM change_log
WHERE workstream_id = $1
RETURNING id, workstream_id, seq, parent_change_log_id, message, title, content_markdown, created_by, created_at
`

type CreateChangeLogParams struct {
	WorkstreamID      uuid.UUID     `json:"workstream_id"`
	ParentChangeLogID uuid.NullUUID `json:"parent_change_log_id"`
	Message           string        `json:"message"`
	Title             string        `json:"title"`
	ContentMarkdown   string        `json:"content_markdown"`
	CreatedBy         uuid.UUID     `json:"created_by"`
}

// The caller locks the workstream before this statement, serializing sequence
// assignment and expected-parent validation in the surrounding transaction.
func (q *Queries) CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, createChangeLog,
		arg.WorkstreamID,
		arg.ParentChangeLogID,
		arg.Message,
		arg.Title,
		arg.ContentMarkdown,
		arg.CreatedBy,
	)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.WorkstreamID,
		&i.Seq,
		&i.ParentChangeLogID,
		&i.Message,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createDocumentWorkstream = `-- name: CreateDocumentWorkstream :one
INSERT INTO document_workstream (document_id, owner_id, name, base_revision_id)
VALUES (
    $1,
    $2,
    btrim($3),
    $4
)
RETURNING id, document_id, owner_id, name, base_revision_id, status, created_at, updated_at, submitted_at, abandoned_at
`

type CreateDocumentWorkstreamParams struct {
	DocumentID     uuid.UUID `json:"document_id"`
	OwnerID        uuid.UUID `json:"owner_id"`
	Name           string    `json:"name"`
	BaseRevisionID uuid.UUID `json:"base_revision_id"`
}

func (q *Queries) CreateDocumentWorkstream(ctx context.Context, arg CreateDocumentWorkstreamParams) (DocumentWorkstream, error) {
	row := q.db.QueryRow(ctx, createDocumentWorkstream,
		arg.DocumentID,
		arg.OwnerID,
		arg.Name,
		arg.BaseRevisionID,
	)
	var i DocumentWorkstream
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OwnerID,
		&i.Name,
		&i.BaseRevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.AbandonedAt,
	)
	return i, err
}

const getChangeLogByID = `-- name: GetChangeLogByID :one
SELECT cl.id, cl.workstream_id, cl.seq, cl.parent_change_log_id, cl.message, cl.title, cl.content_markdown, cl.created_by, cl.created_at
FROM change_log cl
JOIN document_workstream w ON w.id = cl.workstream_id
WHERE cl.id = $1
  AND cl.workstream_id = $2
  AND w.document_id = $3
`

type GetChangeLogByIDParams struct {
	ID           uuid.UUID `json:"id"`
	WorkstreamID uuid.UUID `json:"workstream_id"`
	DocumentID   uuid.UUID `json:"document_id"`
}

func (q *Queries) GetChangeLogByID(ctx context.Context, arg GetChangeLogByIDParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, getChangeLogByID, arg.ID, arg.WorkstreamID, arg.DocumentID)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.WorkstreamID,
		&i.Seq,
		&i.ParentChangeLogID,
		&i.Message,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getChangeLogForChangeRequest = `-- name: GetChangeLogForChangeRequest :one
SELECT cl.id, cl.workstream_id, cl.seq, cl.parent_change_log_id, cl.message, cl.title, cl.content_markdown, cl.created_by, cl.created_at
FROM change_log cl
JOIN change_request cr ON cr.workstream_id = cl.workstream_id
WHERE cr.id = $1 AND cl.id = $2
`

type GetChangeLogForChangeRequestParams struct {
	ID   uuid.UUID `json:"id"`
	ID_2 uuid.UUID `json:"id_2"`
}

func (q *Queries) GetChangeLogForChangeRequest(ctx context.Context, arg GetChangeLogForChangeRequestParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, getChangeLogForChangeRequest, arg.ID, arg.ID_2)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.WorkstreamID,
		&i.Seq,
		&i.ParentChangeLogID,
		&i.Message,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentWorkstreamByID = `-- name: GetDocumentWorkstreamByID :one
SELECT id, document_id, owner_id, name, base_revision_id, status, created_at, updated_at, submitted_at, abandoned_at
FROM document_workstream
WHERE id = $1 AND document_id = $2 AND owner_id = $3
`

type GetDocumentWorkstreamByIDParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	OwnerID    uuid.UUID `json:"owner_id"`
}

func (q *Queries) GetDocumentWorkstreamByID(ctx context.Context, arg GetDocumentWorkstreamByIDParams) (DocumentWorkstream, error) {
	row := q.db.QueryRow(ctx, getDocumentWorkstreamByID, arg.ID, arg.DocumentID, arg.OwnerID)
	var i DocumentWorkstream
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OwnerID,
		&i.Name,
		&i.BaseRevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.AbandonedAt,
	)
	return i, err
}

const getDocumentWorkstreamForRead = `-- name: GetDocumentWorkstreamForRead :one
SELECT id, document_id, owner_id, name, base_revision_id, status, created_at, updated_at, submitted_at, abandoned_at
FROM document_workstream
WHERE id = $1 AND document_id = $2
`

type GetDocumentWorkstreamForReadParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
}

// Read path: no owner filter. Reading a branch needs project access, which
// the service checks; writing to one still needs to be its owner.
func (q *Queries) GetDocumentWorkstreamForRead(ctx context.Context, arg GetDocumentWorkstreamForReadParams) (DocumentWorkstream, error) {
	row := q.db.QueryRow(ctx, getDocumentWorkstreamForRead, arg.ID, arg.DocumentID)
	var i DocumentWorkstream
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OwnerID,
		&i.Name,
		&i.BaseRevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.AbandonedAt,
	)
	return i, err
}

const getDocumentWorkstreamForUpdate = `-- name: GetDocumentWorkstreamForUpdate :one
SELECT id, document_id, owner_id, name, base_revision_id, status, created_at, updated_at, submitted_at, abandoned_at
FROM document_workstream
WHERE id = $1 AND document_id = $2 AND owner_id = $3 AND status = 'active'
FOR UPDATE
`

type GetDocumentWorkstreamForUpdateParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	OwnerID    uuid.UUID `json:"owner_id"`
}

// Locks the active workstream before appending a log or submitting it.
func (q *Queries) GetDocumentWorkstreamForUpdate(ctx context.Context, arg GetDocumentWorkstreamForUpdateParams) (DocumentWorkstream, error) {
	row := q.db.QueryRow(ctx, getDocumentWorkstreamForUpdate, arg.ID, arg.DocumentID, arg.OwnerID)
	var i DocumentWorkstream
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OwnerID,
		&i.Name,
		&i.BaseRevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.AbandonedAt,
	)
	return i, err
}

const getLatestChangeLog = `-- name: GetLatestChangeLog :one
SELECT cl.id, cl.workstream_id, cl.seq, cl.parent_change_log_id, cl.message, cl.title, cl.content_markdown, cl.created_by, cl.created_at
FROM change_log cl
JOIN document_workstream w ON w.id = cl.workstream_id
WHERE cl.workstream_id = $1
  AND w.document_id = $2
ORDER BY cl.seq DESC
LIMIT 1
`

type GetLatestChangeLogParams struct {
	WorkstreamID uuid.UUID `json:"workstream_id"`
	DocumentID   uuid.UUID `json:"document_id"`
}

func (q *Queries) GetLatestChangeLog(ctx context.Context, arg GetLatestChangeLogParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, getLatestChangeLog, arg.WorkstreamID, arg.DocumentID)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.WorkstreamID,
		&i.Seq,
		&i.ParentChangeLogID,
		&i.Message,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getPreviousChangeLog = `-- name: GetPreviousChangeLog :one
SELECT previous.id, previous.workstream_id, previous.seq, previous.parent_change_log_id, previous.message, previous.title, previous.content_markdown, previous.created_by, previous.created_at
FROM change_log current
JOIN change_log previous
  ON previous.workstream_id = current.workstream_id
 AND previous.seq = current.seq - 1
WHERE current.id = $1 AND current.workstream_id = $2
`

type GetPreviousChangeLogParams struct {
	ID           uuid.UUID `json:"id"`
	WorkstreamID uuid.UUID `json:"workstream_id"`
}

func (q *Queries) GetPreviousChangeLog(ctx context.Context, arg GetPreviousChangeLogParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, getPreviousChangeLog, arg.ID, arg.WorkstreamID)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.WorkstreamID,
		&i.Seq,
		&i.ParentChangeLogID,
		&i.Message,
		&i.Title,
		&i.ContentMarkdown,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listChangeLogsForChangeRequest = `-- name: ListChangeLogsForChangeRequest :many
SELECT cl.id, cl.workstream_id, cl.seq, cl.parent_change_log_id, cl.message, cl.title, cl.content_markdown, cl.created_by, cl.created_at
FROM change_log cl
JOIN change_request cr ON cr.workstream_id = cl.workstream_id
WHERE cr.id = $1
ORDER BY cl.seq ASC
`

// Included logs become visible with their Change Request. The caller first
// authorizes access to the CR, so these queries scope identity to that CR.
func (q *Queries) ListChangeLogsForChangeRequest(ctx context.Context, id uuid.UUID) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsForChangeRequest, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeLog{}
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkstreamID,
			&i.Seq,
			&i.ParentChangeLogID,
			&i.Message,
			&i.Title,
			&i.ContentMarkdown,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeLogsForWorkstream = `-- name: ListChangeLogsForWorkstream :many
SELECT cl.id, cl.workstream_id, cl.seq, cl.parent_change_log_id, cl.message, cl.title, cl.content_markdown, cl.created_by, cl.created_at
FROM change_log cl
JOIN document_workstream w ON w.id = cl.workstream_id
WHERE cl.workstream_id = $1
  AND w.document_id = $2
ORDER BY cl.seq ASC
`

type ListChangeLogsForWorkstreamParams struct {
	WorkstreamID uuid.UUID `json:"workstream_id"`
	DocumentID   uuid.UUID `json:"document_id"`
}

// Saved logs are the published part of a branch, so these read paths join
// only to prove the log belongs to this document.
func (q *Queries) ListChangeLogsForWorkstream(ctx context.Context, arg ListChangeLogsForWorkstreamParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsForWorkstream, arg.WorkstreamID, arg.DocumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChangeLog{}
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkstreamID,
			&i.Seq,
			&i.ParentChangeLogID,
			&i.Message,
			&i.Title,
			&i.ContentMarkdown,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentWorkstreams = `-- name: ListDocumentWorkstreams :many
SELECT
    w.id, w.document_id, w.owner_id, w.name, w.base_revision_id, w.status, w.created_at, w.updated_at, w.submitted_at, w.abandoned_at,
    u.name AS owner_name,
    (SELECT count(*) FROM change_log cl WHERE cl.workstream_id = w.id) AS change_log_count
FROM document_workstream w
JOIN user_account u ON u.id = w.owner_id
WHERE w.document_id = $1
ORDER BY (w.status = 'active') DESC, w.updated_at DESC
`

type ListDocumentWorkstreamsRow struct {
	ID             uuid.UUID          `json:"id"`
	DocumentID     uuid.UUID          `json:"document_id"`
	OwnerID        uuid.UUID          `json:"owner_id"`
	Name           string             `json:"name"`
	BaseRevisionID uuid.UUID          `json:"base_revision_id"`
	Status         string             `json:"status"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	AbandonedAt    pgtype.Timestamptz `json:"abandoned_at"`
	OwnerName      string             `json:"owner_name"`
	ChangeLogCount int64              `json:"change_log_count"`
}

// Every branch on the document, whoever owns it: a branch is visible to the
// whole project, and the caller's project access is checked before this runs.
// Active first, then most recently touched, so the list opens on live work.
func (q *Queries) ListDocumentWorkstreams(ctx context.Context, documentID uuid.UUID) ([]ListDocumentWorkstreamsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentWorkstreams, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentWorkstreamsRow{}
	for rows.Next() {
		var i ListDocumentWorkstreamsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.OwnerID,
			&i.Name,
			&i.BaseRevisionID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubmittedAt,
			&i.AbandonedAt,
			&i.OwnerName,
			&i.ChangeLogCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenDocumentWorkstream = `-- name: ReopenDocumentWorkstream :one
UPDATE document_workstream
SET status = 'active', submitted_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'submitted'
RETURNING id, document_id, owner_id, name, base_revision_id, status, created_at, updated_at, submitted_at, abandoned_at
`

// Closing a Change Request hands the branch back to its author. Scoped to
// 'submitted' so it can never resurrect an abandoned branch.
func (q *Queries) ReopenDocumentWorkstream(ctx context.Context, id uuid.UUID) (DocumentWorkstream, error) {
	row := q.db.QueryRow(ctx, reopenDocumentWorkstream, id)
	var i DocumentWorkstream
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OwnerID,
		&i.Name,
		&i.BaseRevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.AbandonedAt,
	)
	return i, err
}

const submitDocumentWorkstream = `-- name: SubmitDocumentWorkstream :one
UPDATE document_workstream
SET status = 'submitted', submitted_at = now(), updated_at = now()
WHERE id = $1 AND document_id = $2 AND owner_id = $3 AND status = 'active'
RETURNING id, document_id, owner_id, name, base_revision_id, status, created_at, updated_at, submitted_at, abandoned_at
`

type SubmitDocumentWorkstreamParams struct {
	ID         uuid.UUID `json:"id"`
	DocumentID uuid.UUID `json:"document_id"`
	OwnerID    uuid.UUID `json:"owner_id"`
}

func (q *Queries) SubmitDocumentWorkstream(ctx context.Context, arg SubmitDocumentWorkstreamParams) (DocumentWorkstream, error) {
	row := q.db.QueryRow(ctx, submitDocumentWorkstream, arg.ID, arg.DocumentID, arg.OwnerID)
	var i DocumentWorkstream
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.OwnerID,
		&i.Name,
		&i.BaseRevisionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubmittedAt,
		&i.AbandonedAt,
	)
	return i, err
}

const touchDocumentWorkstream = `-- name: TouchDocumentWorkstream :exec
UPDATE document_workstream
SET updated_at = now()
WHERE id = $1
`

func (q *Queries) TouchDocumentWorkstream(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchDocumentWorkstream, id)
	return err
}
